# Generated by Django 4.2.17 on 2025-01-11 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("quality", "Quality"),
                            ("maintenance", "Maintenance"),
                            ("safety", "Safety"),
                            ("inventory", "Inventory"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("source_machine", models.CharField(max_length=100)),
                ("source_department", models.CharField(max_length=100)),
                ("source_operator", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("efficiency", "Efficiency"),
                            ("quality", "Quality"),
                            ("productivity", "Productivity"),
                            ("safety", "Safety"),
                            ("cost", "Cost"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unit", models.CharField(max_length=50)),
                ("target_value", models.FloatField()),
                ("current_value", models.FloatField()),
                (
                    "warning_threshold",
                    models.FloatField(help_text="Threshold for warning alerts"),
                ),
                (
                    "critical_threshold",
                    models.FloatField(help_text="Threshold for critical alerts"),
                ),
                (
                    "trend_period_days",
                    models.IntegerField(
                        default=30, help_text="Number of days to analyze for trends"
                    ),
                ),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("kpi_summary", "KPI Summary"),
                            ("event_analysis", "Event Analysis"),
                            ("trend_analysis", "Trend Analysis"),
                            ("alert_summary", "Alert Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "report_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "event_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of event types",
                        max_length=255,
                    ),
                ),
                (
                    "departments",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of departments",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("generated_by", models.CharField(max_length=100)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                (
                    "included_kpis",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="analytics.kpi"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPIHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="analytics.kpi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "KPI histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("threshold_value", models.FloatField()),
                ("current_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=100)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="analytics.kpi",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="analytics.analyticsevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "key")},
            },
        ),
        migrations.CreateModel(
            name="DataAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("average", "Average"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("count", "Count"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("production", "Production"),
                            ("quality", "Quality"),
                            ("maintenance", "Maintenance"),
                            ("safety", "Safety"),
                            ("inventory", "Inventory"),
                        ],
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("value", models.FloatField(blank=True, null=True)),
                ("count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "source_kpi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.kpi",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregation_type", "time_period"],
                        name="analytics_d_aggrega_5c5803_idx",
                    )
                ],
                "unique_together": {("name", "aggregation_type", "time_period")},
            },
        ),
    ]
